"use client";

import { useEffect, useState } from "react";
import { Activity, ArrowLeft, Bookmark, Eye, Heart, Link2, MessageCircle, Send, X } from "lucide-react";
import { apiFetch, getSavedUser } from "@/lib/api";
import { Avatar } from "@/components/ui/Avatar";
import ThreadedCommentTree, { type ThreadComment } from "@/components/social/ThreadedCommentTree";

type UserRef = { id: string; name: string; username: string; avatarUrl?: string | null };
type Media = { publicUrl: string | null; mimeType: string };
type QuotePost = { id: string; text: string; createdAt: string; author: UserRef; media?: Media[] };
type Post = { id: string; text: string; createdAt: string; likes: number; comments: number; reposts: number; saves?: number; views?: number; author: UserRef; project?: { name: string; slug: string } | null; linkUrl?: string | null; media?: Media[]; quotePost?: QuotePost | null; commentsTree: ThreadComment[] };

const nav = (path: string) => { window.history.pushState({}, "", path); window.dispatchEvent(new PopStateEvent("popstate")); };
const ago = (value: string) => { const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000)); if (seconds < 60) return "now"; if (seconds < 3600) return `${Math.floor(seconds / 60)}m`; if (seconds < 86400) return `${Math.floor(seconds / 3600)}h`; return `${Math.floor(seconds / 86400)}d`; };

function UserButton({ user }: { user: UserRef }) { return <button className="post-detail-author-button" onClick={() => nav(`/profile/${encodeURIComponent(user.username)}`)}><Avatar user={user} size="sm" /><span><strong>{user.name}</strong><small>@{user.username}</small></span></button>; }

function QuoteCard({ quote }: { quote: QuotePost }) { const open = () => window.dispatchEvent(new CustomEvent("nerdding:open-post", { detail: { postId: quote.id } })); return <article className="post-detail-quote" role="button" tabIndex={0} onClick={open} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); open(); } }}><div className="post-detail-quote-label">QUOTED POST</div><UserButton user={quote.author} /><p>{quote.text}</p>{quote.media?.length ? <div className="post-detail-media">{quote.media.slice(0, 4).map((media, index) => media.publicUrl ? (media.mimeType.startsWith("video/") ? <video key={index} src={media.publicUrl} controls onClick={(event) => event.stopPropagation()} /> : <img key={index} src={media.publicUrl} alt="" loading="lazy" />) : null)}</div> : null}<small>{ago(quote.createdAt)} · Open post</small></article>; }

export default function PostDetailSurface({ postId, onClose, isPanel = false }: { postId: string; onClose?: () => void; isPanel?: boolean }) {
  const [post, setPost] = useState<Post | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [text, setText] = useState("");
  const [busy, setBusy] = useState(false);
  const [saved, setSaved] = useState(false);
  const load = async () => { setLoading(true); setError(""); try { const response = await apiFetch<{ data: Post }>(`/social/posts/${encodeURIComponent(postId)}`); setPost(response.data); setSaved(Boolean(response.data.saves && response.data.saves > 0)); } catch (errorValue) { setError(errorValue instanceof Error ? errorValue.message : "Post could not be loaded"); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [postId]);
  const addComment = async (parentId: string | null, body: string) => { if (!getSavedUser() || busy) return; setBusy(true); try { await apiFetch(`/social/posts/${encodeURIComponent(postId)}/comments`, { method: "POST", body: JSON.stringify({ body, parentId }) }); await load(); } catch (errorValue) { setError(errorValue instanceof Error ? errorValue.message : "Comment could not be posted"); } finally { setBusy(false); } };
  const panelHeader = isPanel ? <header className="post-detail-panel-header"><div><div className="post-detail-panel-label">POST DETAIL</div><h2>Active post</h2></div>{onClose && <button className="post-detail-panel-close" onClick={onClose} aria-label="Close active post"><X size={18} /></button>}</header> : null;
  if (loading) return isPanel ? <div className="post-detail-panel">{panelHeader}<div className="post-detail-panel-inner"><div className="skeleton-block skeleton-hero" /></div></div> : <div className="nerdd-route-surface"><div className="skeleton-block skeleton-hero" /></div>;
  if (!post) return isPanel ? <div className="post-detail-panel">{panelHeader}<div className="post-detail-panel-inner"><div className="empty-state"><strong>Post could not be loaded.</strong><span>{error}</span><button className="outline-button" onClick={() => void load()}>Try again</button></div></div></div> : <div className="nerdd-route-surface"><div className="empty-state"><strong>Post could not be loaded.</strong><span>{error}</span><button className="outline-button" onClick={() => void load()}>Try again</button></div></div>;
  const content = <><article className="post-detail-card"><div className="post-detail-card-head"><UserButton user={post.author} /><span className="post-detail-time">{new Date(post.createdAt).toLocaleString()}</span>{onClose && !isPanel && <button className="icon-btn" onClick={onClose} aria-label="Close"><X size={18} /></button>}</div><p className="post-detail-copy">{post.text}</p>{post.quotePost ? <QuoteCard quote={post.quotePost} /> : null}{post.media?.length ? <div className="post-detail-media">{post.media.slice(0, 4).map((media, index) => media.publicUrl ? (media.mimeType.startsWith("video/") ? <video key={index} src={media.publicUrl} controls /> : <img key={index} src={media.publicUrl} alt="" loading="lazy" />) : null)}</div> : null}{post.project && <button className="outline-button post-detail-project" onClick={() => window.dispatchEvent(new CustomEvent("nerdding:open-project", { detail: { slug: post.project?.slug } }))}>Mentioned project: {post.project.name}</button>}{post.linkUrl ? <a className="post-detail-link" href={post.linkUrl} target="_blank" rel="noreferrer"><Link2 size={14} />{post.linkUrl.replace(/^https?:\/\//, "")}</a> : null}<div className="post-detail-actionbar"><div><span title="Likes"><Heart size={15} /> {post.likes}</span><span title="Comments"><MessageCircle size={15} /> {post.comments}</span><span title="Amplifies"><Activity size={15} /> {post.reposts}</span></div><div><span title="Views"><Eye size={15} /> {post.views ?? 0}</span><button title="Save" className={saved ? "action-active" : ""} onClick={async () => { try { const response = await apiFetch<{ data: { active: boolean } }>(`/posts/${post.id}/save`, { method: "POST" }); setSaved(response.data.active); await load(); } catch { setError("Post could not be saved"); } }}><Bookmark size={15} fill={saved ? "currentColor" : "none"} /> Save</button></div></div></article><section className="post-detail-comments"><div className="eyebrow">REPLIES</div><h2>Replies</h2><div className="post-detail-compose"><Avatar user={getSavedUser() ?? { id: "guest", name: "Guest", username: "guest" }} size="xs" /><input value={text} onChange={(event) => setText(event.target.value)} placeholder="Write a reply..." onKeyDown={(event) => { if (event.key === "Enter" && text.trim()) { void addComment(null, text.trim()); setText(""); } }} /><button disabled={!text.trim() || busy} onClick={() => { void addComment(null, text.trim()); setText(""); }}><Send size={14} /></button></div><ThreadedCommentTree comments={post.commentsTree ?? []} onReply={addComment} /></section></>;
  return isPanel ? <div className="post-detail-panel">{panelHeader}<div className="post-detail-panel-inner">{content}</div></div> : <div className="nerdd-route-surface"><div className="view post-detail-view">{!onClose && <button className="back-button" onClick={() => nav("/home")}><ArrowLeft size={15} /> Back to feed</button>}{content}</div></div>;
}
