"use client";
import { useEffect,useState } from "react";
import { ArrowLeft, Heart, Send } from "lucide-react";
import { apiFetch,getSavedUser } from "@/lib/api";
import { Avatar } from "@/components/ui/Avatar";

type Comment={id:string;parentId:string|null;body:string;createdAt:string;author:{id:string;name:string;username:string;avatarUrl?:string|null};replies:Comment[]};type Post={id:string;text:string;createdAt:string;likes:number;comments:number;reposts:number;author:{id:string;name:string;username:string;avatarUrl?:string|null};project?:{name:string;slug:string}|null;commentsTree:Comment[]};
const nav=(p:string)=>{window.history.pushState({},"",p);window.dispatchEvent(new PopStateEvent("popstate"))};
function CommentTree({items,postId,onReply}:{items:Comment[];postId:string;onReply:(parentId:string,body:string)=>Promise<void>}){return <div className="post-comments-tree">{items.map(item=><CommentNode key={item.id} item={item} postId={postId} onReply={onReply}/>)}</div>}
function CommentNode({item,postId,onReply}:{item:Comment;postId:string;onReply:(parentId:string,body:string)=>Promise<void>}){const[text,setText]=useState("");const[open,setOpen]=useState(false);return <div className="post-comment-node"><div className="post-comment-row"><Avatar user={{id:item.author.id,name:item.author.name,username:item.author.username,avatarUrl:item.author.avatarUrl}} size="xs"/><div><strong>{item.author.name}</strong><small>@{item.author.username} · {new Date(item.createdAt).toLocaleString()}</small><p>{item.body}</p><button onClick={()=>setOpen(!open)}>Reply</button></div></div>{open&&<div className="post-reply-box"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Write a reply…" onKeyDown={e=>{if(e.key==="Enter"&&text.trim()){void onReply(item.id,text.trim());setText("")}}}/><button disabled={!text.trim()} onClick={()=>{void onReply(item.id,text.trim());setText("")}}><Send size={14}/></button></div>}{item.replies.length>0&&<CommentTree items={item.replies} postId={postId} onReply={onReply}/>}</div>}
export default function PostDetailSurface({postId}:{postId:string}){const[post,setPost]=useState<Post|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[text,setText]=useState("");const[busy,setBusy]=useState(false);const load=async()=>{setLoading(true);try{const r=await apiFetch<{data:Post}>(`/social/posts/${encodeURIComponent(postId)}`);setPost(r.data)}catch(e){setError(e instanceof Error?e.message:"Post could not be loaded")}finally{setLoading(false)}};useEffect(()=>{void load()},[postId]);const addComment=async(parentId:string|null,body:string)=>{if(!getSavedUser()||busy)return;setBusy(true);try{await apiFetch(`/social/posts/${encodeURIComponent(postId)}/comments`,{method:"POST",body:JSON.stringify({body,parentId})});await load()}catch(e){setError(e instanceof Error?e.message:"Comment could not be posted")}finally{setBusy(false)}};if(loading)return <div className="nerdd-route-surface"><div className="skeleton-block skeleton-hero"/></div>;if(!post)return <div className="nerdd-route-surface"><div className="empty-state"><strong>Post could not be loaded.</strong><span>{error}</span><button className="outline-button" onClick={()=>void load()}>Try again</button></div></div>;return <div className="nerdd-route-surface"><div className="view post-detail-view"><button className="back-button" onClick={()=>nav("/home")}><ArrowLeft size={15}/> Back to feed</button><article className="post-detail-card"><div className="post-detail-author"><Avatar user={{id:post.author.id,name:post.author.name,username:post.author.username,avatarUrl:post.author.avatarUrl}} size="md"/><span><strong>{post.author.name}</strong><small>@{post.author.username} · {new Date(post.createdAt).toLocaleString()}</small></span></div><p className="post-detail-copy">{post.text}</p>{post.project&&<button className="outline-button" onClick={()=>nav(`/project/${encodeURIComponent(post.project!.slug)}`)}>Mentioned project: {post.project.name}</button>}<div className="post-detail-stats"><span><Heart size={15}/> {post.likes}</span><span>{post.comments} comments</span></div></article><section className="post-detail-comments"><div className="eyebrow">CONVERSATION</div><h2>Comments</h2><div className="post-detail-compose"><Avatar user={{...post.author,...(getSavedUser()??{})}} size="xs"/><input value={text} onChange={e=>setText(e.target.value)} placeholder="Add a thoughtful comment…" onKeyDown={e=>{if(e.key==="Enter"&&text.trim()){void addComment(null,text.trim());setText("")}}}/><button disabled={!text.trim()||busy} onClick={()=>{void addComment(null,text.trim());setText("")}}><Send size={14}/></button></div><CommentTree items={post.commentsTree??[]} postId={post.id} onReply={addComment}/></section></div></div>}
