"use client";
import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { Check, Crown } from "lucide-react";
import { apiFetch } from "@/lib/api";

type Aff={id:string;name:string;slug:string;role:string;verified:boolean;timeline?:Array<{id:string;role:string;eventType:string;createdAt:string}>};
type Profile={buildHistory:Array<{id:string;createdAt:string;projectName:string;projectSlug:string;text:string}>;affiliations:Aff[]};
const css=`.nerdd-profile-enhanced{margin-top:18px;padding-top:18px;border-top:1px solid #eee8e1}.nerdd-profile-enhanced .eyebrow{margin-bottom:10px}.nerdd-profile-history{display:grid;gap:0}.nerdd-history-item{position:relative;display:flex;gap:10px;padding:9px 0 9px 12px;border-left:1px dashed #d9d0c7}.nerdd-history-item:before{content:"";position:absolute;left:-4px;top:14px;width:7px;height:7px;border-radius:50%;background:#d85b32}.nerdd-history-item strong{font-size:10px;display:block}.nerdd-history-item p{font-size:9px;color:#6f665e;margin:3px 0;line-height:1.45}.nerdd-history-item small{font-size:8px;color:#9a9087}.nerdd-affiliation-history{display:grid;gap:12px}.nerdd-affiliation-card{border:1px solid #e3dcd4;border-radius:10px;padding:10px;background:#fcfaf6}.nerdd-affiliation-card>div:first-child{display:flex;justify-content:space-between;gap:8px}.nerdd-affiliation-card strong{font-size:11px}.nerdd-affiliation-card small{display:block;font-size:8px;color:#91877e;margin-top:2px}.nerdd-role-line{display:flex;gap:8px;align-items:flex-start;margin-top:9px;padding-top:8px;border-top:1px solid #eee8e1}.nerdd-role-line svg{margin-top:1px;color:#d85b32}.nerdd-role-line span{font-size:9px}.nerdd-role-line time{display:block;font-size:8px;color:#9a9087;margin-top:2px}`;
export default function ProfileHistoryLayer(){const[data,setData]=useState<Profile|null>(null);const[mount,setMount]=useState<HTMLElement|null>(null);const load=()=>{const path=window.location.pathname;if(!path.startsWith("/profile/")){setData(null);setMount(null);return}const username=decodeURIComponent(path.split("/")[2]||"");if(!username)return;apiFetch<{data:Profile}>(`/social/users/${encodeURIComponent(username)}/profile-live`).then(r=>setData(r.data)).catch(()=>setData(null));const host=document.querySelector<HTMLElement>(".profile-side-card");if(!host){setMount(null);return}let node=host.querySelector<HTMLElement>(".nerdd-profile-history-mount");if(!node){node=document.createElement("div");node.className="nerdd-profile-history-mount";host.appendChild(node)}setMount(node)};useEffect(()=>{load();const onPop=()=>window.setTimeout(load,0);window.addEventListener("popstate",onPop);return()=>{window.removeEventListener("popstate",onPop);document.querySelectorAll(".nerdd-profile-history-mount").forEach(x=>x.remove())}},[]);if(!data||!mount)return null;return createPortal(<><style>{css}</style><section className="nerdd-profile-enhanced"><div className="eyebrow">BUILD HISTORY</div><div className="nerdd-profile-history">{data.buildHistory.length?data.buildHistory.slice().sort((a,b)=>new Date(a.createdAt).getTime()-new Date(b.createdAt).getTime()).map(item=><div className="nerdd-history-item" key={item.id}><div><strong>{item.projectName}</strong><p>{item.text}</p><small>{new Date(item.createdAt).toLocaleDateString()}</small></div></div>):<div className="profile-side-empty">No project-linked build notes yet.</div>}</div><div className="eyebrow" style={{marginTop:18}}>AGENT AFFILIATIONS</div><div className="nerdd-affiliation-history">{data.affiliations.length?data.affiliations.map(agent=><article className="nerdd-affiliation-card" key={agent.id}><div><span><strong>{agent.name}</strong><small>Current role · {agent.role}</small></span><Check size={14}/></div>{(agent.timeline??[]).map(event=><div className="nerdd-role-line" key={event.id}><Crown size={12}/><span><b>{event.role}</b> · {event.eventType.replace("_"," ")}<time>{new Date(event.createdAt).toLocaleDateString()}</time></span></div>)}</article>):<div className="profile-side-empty">No verified Agent affiliations yet.</div>}</div></section></>,mount)}
