"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Activity, ArrowUpRight, Bookmark, Check, Ellipsis, Eye, Github, Heart, MessageCircle, Plus, Search, Send, Users } from "lucide-react";
import { apiFetch, getSavedUser } from "@/lib/api";
import PostDetailSurface from "@/components/app/PostDetailSurface";

type Tab = "posts" | "projects" | "followers" | "following";
type User = { id:string; name:string; username:string; avatarUrl?:string|null; bio?:string|null; accountType?:string };
type QuotePost = { id:string; author:User; text:string; createdAt:string; media?:Array<{publicUrl:string|null;mimeType:string}>; linkUrl?:string|null; likes?:number; comments?:number; reposts?:number; saves?:number; views?:number };
type Build = { id:string; authorId:string; text:string; createdAt:string; projectId?:string|null; projectName?:string|null; projectSlug?:string|null; linkUrl?:string|null; quotePost?:QuotePost|null; media?:Array<{publicUrl:string|null;mimeType:string}>; likes:number; comments:number; reposts:number; saves:number; views?:number };
type Project = { id:string; name:string; slug:string; description:string; stage:string; github_url?:string|null; created_at?:string|null };
type Person = User & { createdAt?:string };
type Cursor = { createdAt:string; id:string };
type Cache = { items:any[]; cursor:Cursor|null; hasMore:boolean; loading:boolean; error:string };

actionable;
const emptyCache=():Cache=>({items:[],cursor:null,hasMore:true,loading:false,error:""});
const ago=(value:string)=>{const s=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/1000));if(s<60)return "now";if(s<3600)return `${Math.floor(s/60)}m`;if(s<86400)return `${Math.floor(s/3600)}h`;return `${Math.floor(s/86400)}d`;};
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).map(x=>x[0]).join("").slice(0,2).toUpperCase();
const navigatePost=(id:string)=>window.dispatchEvent(new CustomEvent("nerdding:open-profile-post",{detail:{postId:id}}));

function Avatar({user,size=42}:{user:User;size?:number}){return <span className="home-avatar home-avatar-md profile-tab-avatar" style={{width:size,height:size}}>{user.avatarUrl?<img src={user.avatarUrl} alt=""/>:initials(user.name)}</span>}

function SkeletonList({kind}:{kind:Tab}){return <div className={`profile-tab-skeleton-list profile-skeleton-${kind}`} aria-busy="true">{Array.from({length:5},(_,i)=><div className="profile-tab-skeleton-row" key={i}><i/><span/><b/><em/></div>)}</div>}

function QuoteCard({quote}:{quote:QuotePost}){return <article className="nerdd-quote profile-quote-card" role="button" tabIndex={0} onClick={e=>{e.stopPropagation();navigatePost(quote.id)}} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();e.stopPropagation();navigatePost(quote.id)}}}><div className="nerdd-quote-label">QUOTED POST</div><div className="nerdd-quote-head"><span className="nerdd-quote-avatar">{quote.author.avatarUrl?<img src={quote.author.avatarUrl} alt=""/>:initials(quote.author.name)}</span><span><strong>{quote.author.name}</strong><small>@{quote.author.username} · {ago(quote.createdAt)}</small></span></div><div className="nerdd-quote-text">{quote.text}</div>{quote.media?.length?<div className="nerdd-quote-media">{quote.media.slice(0,4).map((m,i)=>m.publicUrl?(m.mimeType.startsWith("video/")?<video key={i} src={m.publicUrl} controls onClick={e=>e.stopPropagation()}/>:<img key={i} src={m.publicUrl} alt="" loading="lazy"/>):null)}</div>:null}</article>}

function BuildCard({build,user}:{build:Build;user:User}){return <article className="home-post profile-build-card profile-post-row" data-post-id={build.id} onClick={()=>navigatePost(build.id)}><div className="home-post-head"><button className="home-author" onClick={e=>e.stopPropagation()}><Avatar user={user}/><span><strong>{user.name}</strong><small>@{user.username} · {ago(build.createdAt)}</small></span></button><button className="home-more" aria-label="Post options" onClick={e=>e.stopPropagation()}><Ellipsis size={17}/></button></div><div className="home-post-copy">{build.text}</div>{build.quotePost?<QuoteCard quote={build.quotePost}/>:null}{build.media?.length?<div className={`home-media home-media-${Math.min(build.media.length,4)}`}>{build.media.slice(0,4).map((m,i)=>m.publicUrl?(m.mimeType.startsWith("video/")?<video key={i} src={m.publicUrl} controls onClick={e=>e.stopPropagation()}/>:<img key={i} src={m.publicUrl} alt="" loading="lazy"/>):null)}</div>:null}{build.projectName?<button className="home-project" onClick={e=>{e.stopPropagation();window.dispatchEvent(new CustomEvent("nerdding:open-project-panel",{detail:{slug:build.projectSlug,id:build.projectId}}))}}><span><strong>{build.projectName}</strong><small>Project</small></span><ArrowUpRight size={14}/></button>:null}{build.linkUrl?<a className="home-link" href={build.linkUrl} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>{build.linkUrl.replace(/^https?:\/\//,"")}</a>:null}<div className="home-actions"><div className="home-actions-left"><button onClick={e=>e.stopPropagation()}><Heart size={16}/><span>{build.likes}</span></button><button onClick={e=>{e.stopPropagation();navigatePost(build.id)}}><MessageCircle size={16}/><span>{build.comments}</span></button><button data-action="amplify" onClick={e=>e.stopPropagation()}><Activity size={16}/><span>{build.reposts}</span></button></div><div className="home-actions-right"><span className="home-views"><Eye size={14}/>{build.views??0} views</span><button aria-label="Save post" onClick={e=>e.stopPropagation()}><Bookmark size={16}/><span>Save</span></button><button aria-label="Send post" onClick={e=>e.stopPropagation()}><Send size={16}/><span>Send</span></button></div></div></article>}

function ProjectCard({project}:{project:Project}){return <button className="profile-project-card-modern profile-project-live" onClick={()=>window.dispatchEvent(new CustomEvent("nerdding:open-project-panel",{detail:{slug:project.slug,id:project.id}}))}><div className="profile-project-card-top"><span>{project.stage}</span>{project.github_url?<Github size={15}/>:null}</div><h3>{project.name}</h3><p>{project.description}</p><small>{project.created_at?new Date(project.created_at).toLocaleDateString():""}</small></button>}
function PersonRow({person}:{person:Person}){return <button className="profile-person-row" onClick={()=>window.dispatchEvent(new CustomEvent("nerdding:open-profile-route",{detail:{username:person.username}}))}><Avatar user={person} size={42}/><span><strong>{person.name}</strong><small>@{person.username}</small>{person.bio?<em>{person.bio}</em>:null}</span><ArrowUpRight size={15}/></button>}

export default function ProfileSectionTabsV2({username}:{username:string}){
  const [summary,setSummary]=useState<any>(null); const [tab,setTab]=useState<Tab>("posts"); const [query,setQuery]=useState(""); const [cache,setCache]=useState<Record<Tab,Cache>>({posts:emptyCache(),projects:emptyCache(),followers:emptyCache(),following:emptyCache()}); const [activePostId,setActivePostId]=useState<string|null>(null); const scrollRef=useRef<HTMLDivElement|null>(null); const own=getSavedUser()?.username?.toLowerCase()===username.toLowerCase(); const current=cache[tab];
  const loadSummary=async()=>{try{const r=await apiFetch<{data:any}>(`/social/users/${encodeURIComponent(username)}/profile-summary`);setSummary(r.data)}catch{try{const r=await apiFetch<{data:any}>(`/social/users/${encodeURIComponent(username)}/profile-live`);setSummary(r.data)}catch{setSummary(null)}}};
  useEffect(()=>{void loadSummary();setTab("posts");setQuery("");setActivePostId(null);setCache({posts:emptyCache(),projects:emptyCache(),followers:emptyCache(),following:emptyCache()})},[username]);
  useEffect(()=>{const onOpen=(e:Event)=>{const id=(e as CustomEvent<{postId?:string}>).detail?.postId;if(id&&window.location.pathname.startsWith("/profile/"))setActivePostId(id)};window.addEventListener("nerdding:open-profile-post",onOpen);return()=>window.removeEventListener("nerdding:open-profile-post",onOpen)},[]);
  useEffect(()=>{const onRoute=(e:Event)=>{const u=(e as CustomEvent<{username?:string}>).detail?.username;if(u){window.history.pushState({},"",`/profile/${encodeURIComponent(u)}`);window.dispatchEvent(new PopStateEvent("popstate"))}};window.addEventListener("nerdding:open-profile-route",onRoute);return()=>window.removeEventListener("nerdding:open-profile-route",onRoute)},[]);
  const loadPage=async(kind:Tab,reset=true)=>{const old=cache[kind];if(old.loading||(!old.hasMore&&!reset))return;setCache(v=>({...v,[kind]:{...v[kind],loading:true,error:"",items:reset?[]:v[kind].items,cursor:reset?null:v[kind].cursor,hasMore:true}}));try{const p=new URLSearchParams({type:kind,limit:"15"});if(query.trim())p.set("q",query.trim());if(!reset&&old.cursor){p.set("cursorCreatedAt",old.cursor.createdAt);p.set("cursorId",old.cursor.id)}const r=await apiFetch<{data:{items:any[];hasMore:boolean;nextCursor:Cursor|null}}>(`/social/users/${encodeURIComponent(username)}/profile-items?${p}`);setCache(v=>({...v,[kind]:{items:reset?r.data.items:[...v[kind].items,...r.data.items].filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i),cursor:r.data.nextCursor,hasMore:r.data.hasMore,loading:false,error:""}}))}catch(e){setCache(v=>({...v,[kind]:{...v[kind],loading:false,error:e instanceof Error?e.message:"Unable to load this section"}}))}};
  useEffect(()=>{void loadPage(tab,true)},[tab,query,username]);
  useEffect(()=>{const node=scrollRef.current;if(!node)return;const sentinel=document.createElement("div");sentinel.className="profile-tab-sentinel";node.appendChild(sentinel);const ob=new IntersectionObserver(([entry])=>{if(entry.isIntersecting)void loadPage(tab,false)},{root:node,rootMargin:"320px"});ob.observe(sentinel);return()=>{ob.disconnect();sentinel.remove()}},[tab,current.cursor,current.hasMore,current.loading]);
  useEffect(()=>{const style=document.createElement("style");style.dataset.profileTabsV2="true";style.textContent=`.profile-tabs-v2{font-family:'Space Grotesk',sans-serif}.profile-posts-scroll-v2{max-height:calc(100dvh - 270px);overflow:auto;overscroll-behavior:contain;scrollbar-gutter:stable;padding-right:5px}.profile-tab-panel{min-width:0}.profile-tab-skeleton-list{display:grid;gap:10px}.profile-tab-skeleton-row{height:120px;border:1px solid #e7e0d6;border-radius:14px;background:linear-gradient(90deg,#fffdf9 25%,#f4efe7 37%,#fffdf9 63%);background-size:400% 100%;animation:profileShimmer 1.2s ease-in-out infinite}.profile-skeleton-projects .profile-tab-skeleton-row{height:140px}.profile-skeleton-followers .profile-tab-skeleton-row,.profile-skeleton-following .profile-tab-skeleton-row{height:72px}@keyframes profileShimmer{0%{background-position:100% 0}100%{background-position:-100% 0}}.profile-tab-grid{display:grid;gap:10px}.profile-project-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.profile-person-list{display:grid;gap:8px}.profile-empty-box{border:1px dashed #d9d2c9;border-radius:14px;padding:40px 20px;text-align:center;color:#8d8279;background:#fffdf9}.profile-empty-box strong{display:block;color:#332e29;margin-top:8px}.profile-empty-box span{display:block;font-size:10px;margin-top:4px}.profile-tab-btn{font-family:'Space Grotesk',sans-serif}.profile-tab-btn b{font-size:9px;color:#9a9087}@media(max-width:820px){.profile-project-grid{grid-template-columns:1fr}.profile-posts-scroll-v2{max-height:none;overflow:visible;padding-right:0}}`;document.head.appendChild(style);return()=>style.remove()},[]);
  const counts=summary?.stats??{posts:0,projects:0,followers:0,following:0};
  const content=useMemo(()=>{if(current.loading&&current.items.length===0)return <SkeletonList kind={tab}/>;if(current.error&&current.items.length===0)return <div className="profile-empty-box"><Activity size={22}/><strong>Could not load this section</strong><span>{current.error}</span><button className="profile-tab-action" onClick={()=>void loadPage(tab,true)}>Try again</button></div>;if(!current.items.length)return <div className="profile-empty-box"><Users size={22}/><strong>{tab==="posts"?"No build notes yet":tab==="projects"?"No projects yet":tab==="followers"?"No followers yet":"Not following anyone yet"}</strong><span>New activity will appear here when it exists.</span></div>;return tab==="posts"?current.items.map((p:Build)=><BuildCard key={p.id} build={p} user={summary.user}/>):tab==="projects"?current.items.map((p:Project)=><ProjectCard key={p.id} project={p}/>):current.items.map((p:Person)=><PersonRow key={p.id} person={p}/>)},[current.items,current.loading,current.error,tab,summary]);
  return <section className="profile-section-tabs-wrap profile-tabs-v2"><nav className="profile-section-tabs" aria-label="Profile sections">{([['posts','Build Notes'],['projects','Projects'],['followers','Followers'],['following','Following']] as const).map(([id,label])=><button className={`profile-tab-btn ${tab===id?'active':''}`} key={id} onClick={()=>setTab(id as Tab)}><span>{label}</span><b>{Number(counts[id]??0)}</b></button>)}</nav><div className="profile-content-grid"><div className="profile-section-content"><div className="profile-tab-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${tab==='posts'?'build notes':tab}`}/></div>{tab==='posts'&&own?<div className="profile-tab-actionbar"><div className="profile-tab-action-copy"><span className="profile-tab-action-eyebrow">BUILD IN PUBLIC</span><strong>Keep your build log moving.</strong><small>Share progress, experiments and shipped work as posts.</small></div><button className="profile-tab-action" onClick={()=>window.dispatchEvent(new CustomEvent("nerdding:open-create-post"))}><Plus size={15}/> Post a Build</button></div>:null}<div ref={scrollRef} className="profile-posts-scroll-v2 profile-tab-panel">{content}</div></div><div className="profile-right-rail"><div className="profile-post-detail-slot">{activePostId?<PostDetailSurface postId={activePostId} onClose={()=>setActivePostId(null)} isPanel/>:null}</div><aside className="profile-affiliations-rail"><div className="profile-affiliations-rail-head"><div><div className="eyebrow">TRUSTED IDENTITY</div><h3>Affiliations</h3></div></div>{summary?.affiliations?.length?summary.affiliations.map((a:any)=><article className="profile-affiliation-modern" key={a.id}><div className="profile-affiliation-top"><div className="profile-affiliation-name"><span className="profile-affiliation-badge">{a.name.slice(0,1)}</span><span><strong>{a.name}</strong><small>@{a.slug}</small></span></div>{a.verified?<span className="profile-verified-pill"><Check size={12}/> Verified</span>:null}</div><p>{a.role} · {a.type}</p></article>):<div className="profile-empty-box"><Users size={20}/><strong>No affiliations yet</strong><span>Verified affiliations will appear here.</span></div>}</aside></div></div></section>;
}
