"use client";

import { useEffect, useRef, useState } from "react";
import { Activity, ArrowUpRight, Bookmark, Check, Github, Heart, MessageCircle, Plus, Search, Send, Users, X } from "lucide-react";
import { apiFetch, getSavedUser } from "@/lib/api";
import PostDetailSurface from "@/components/app/PostDetailSurface";
import "../profile/profile-polish.css";

type Tab = "posts" | "projects" | "followers" | "following";
type User = { id: string; name: string; username: string; avatarUrl?: string | null; bio?: string | null; accountType?: string };
type Summary = { user: User; stats: { posts: number; projects: number; followers: number; following: number }; affiliations: Affiliation[] };
type Affiliation = { id: string; name: string; slug: string; type: string; verified: boolean; role: string; status?: string };
type QuotePost = { id: string; author: User; text: string; createdAt: string; linkUrl?: string | null; media?: { publicUrl: string | null; mimeType: string }[]; likes?: number; comments?: number; reposts?: number; saves?: number; views?: number };
type Build = { id: string; authorId: string; text: string; createdAt: string; projectId?: string | null; projectName?: string | null; projectSlug?: string | null; linkUrl?: string | null; quotePostId?: string | null; quotePost?: QuotePost | null; media?: { publicUrl: string | null; mimeType: string }[]; likes: number; comments: number; reposts: number; saves: number; views?: number };
type Project = { id: string; name: string; slug: string; description: string; stage: string; github_url?: string | null; created_at?: string | null };
type Person = User & { createdAt?: string };
type Cursor = { createdAt: string; id: string };
type Page<T> = { items: T[]; hasMore: boolean; nextCursor: Cursor | null };
type Cache = { items: unknown[]; cursor: Cursor | null; hasMore: boolean; loading: boolean; error: string; query: string };
const emptyCache = (): Cache => ({ items: [], cursor: null, hasMore: true, loading: false, error: "", query: "" });
const nav = (path: string) => { window.history.pushState({}, "", path); window.dispatchEvent(new PopStateEvent("popstate")); };
const openCreatePost = () => window.dispatchEvent(new CustomEvent("nerdding:open-create-post"));
const openProfilePost = (postId: string) => window.dispatchEvent(new CustomEvent("nerdding:open-profile-post", { detail: { postId } }));
const date = (value?: string | null) => value ? new Date(value).toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" }) : "";
const ago = (value?: string | null) => { if (!value) return ""; const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000)); if (seconds < 60) return "now"; if (seconds < 3600) return `${Math.floor(seconds / 60)}m`; if (seconds < 86400) return `${Math.floor(seconds / 3600)}h`; return `${Math.floor(seconds / 86400)}d`; };
const initials = (name: string) => name.split(/\s+/).filter(Boolean).map((part) => part[0]).join("").slice(0, 2).toUpperCase();

function Avatar({ user, size = 42 }: { user: User; size?: number }) { return <span className="home-avatar profile-tab-avatar" style={{ width: size, height: size }}>{user.avatarUrl ? <img src={user.avatarUrl} alt="" /> : initials(user.name)}</span>; }
function LoadingRows({ kind }: { kind: Tab }) { return <div className={`profile-tab-skeleton-list profile-skeleton-${kind}`}>{Array.from({ length: 3 }, (_, index) => <div className="profile-tab-skeleton-row" key={index}><i /><span /><b /><em /></div>)}</div>; }

function QuoteCard({ quote }: { quote: QuotePost }) {
  const open = () => openProfilePost(quote.id);
  return <article className="nerdd-quote" role="button" tabIndex={0} onClick={(event) => { event.stopPropagation(); open(); }} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); event.stopPropagation(); open(); } }}><div className="nerdd-quote-label">QUOTED POST</div><div className="nerdd-quote-head"><span className="nerdd-quote-avatar">{quote.author.avatarUrl ? <img src={quote.author.avatarUrl} alt="" /> : initials(quote.author.name)}</span><span><strong>{quote.author.name}</strong><small>@{quote.author.username} · {ago(quote.createdAt)}</small></span></div><div className="nerdd-quote-text">{quote.text}</div>{quote.media?.length ? <div className="nerdd-quote-media">{quote.media.slice(0, 4).map((media, index) => media.publicUrl ? (media.mimeType.startsWith("video/") ? <video key={index} src={media.publicUrl} controls onClick={(event) => event.stopPropagation()} /> : <img key={index} src={media.publicUrl} alt="" loading="lazy" />) : null)}</div> : null}</article>;
}

function BuildCard({ build, user }: { build: Build; user: User }) {
  return <article className="home-post profile-build-card profile-post-row" data-post-id={build.id} onClick={() => openProfilePost(build.id)}><div className="home-post-head"><button className="home-author" onClick={(event) => { event.stopPropagation(); nav(`/profile/${encodeURIComponent(user.username)}`); }}><Avatar user={user} size={42} /><span><strong>{user.name}</strong><small>@{user.username} · {ago(build.createdAt)}</small></span></button><button className="home-more" aria-label="Post options" onClick={(event) => event.stopPropagation()}><Activity size={17} /></button></div><div className="home-post-copy">{build.text}</div>{build.quotePost ? <QuoteCard quote={build.quotePost} /> : null}{build.media?.length ? <div className={`home-media home-media-${Math.min(build.media.length, 4)}`}>{build.media.slice(0, 4).map((media, index) => media.publicUrl ? (media.mimeType.startsWith("video/") ? <video key={index} src={media.publicUrl} controls onClick={(event) => event.stopPropagation()} /> : <img key={index} src={media.publicUrl} alt="" loading="lazy" />) : null)}</div> : null}{build.projectName && <button className="home-project" onClick={(event) => { event.stopPropagation(); if (build.projectSlug) nav(`/project/${encodeURIComponent(build.projectSlug)}`); }}><span><strong>{build.projectName}</strong><small>Project</small></span></button>}{build.linkUrl && <a href={build.linkUrl} target="_blank" rel="noreferrer" className="home-link" onClick={(event) => event.stopPropagation()}>{build.linkUrl.replace(/^https?:\/\//, "")}</a>}<div className="home-actions"><div className="home-actions-left"><button onClick={(event) => event.stopPropagation()}><Heart size={16} /><span>{build.likes}</span></button><button onClick={(event) => { event.stopPropagation(); openProfilePost(build.id); }}><MessageCircle size={16} /><span>{build.comments}</span></button><button data-action="amplify" onClick={(event) => event.stopPropagation()}><Activity size={16} /><span>{build.reposts}</span></button></div><div className="home-actions-right"><span className="home-views"><span>{build.views ?? 0} views</span></span><button aria-label="Save post" onClick={(event) => event.stopPropagation()}><Bookmark size={16} /><span>Save</span></button><button data-action="send" aria-label="Send post" onClick={(event) => event.stopPropagation()}><Send size={16} /><span>Send</span></button></div></div></article>;
}

function ProjectCard({ project }: { project: Project }) { return <button className="profile-project-card-modern" onClick={() => nav(`/project/${encodeURIComponent(project.slug)}`)}><div className="profile-project-card-top"><span>{project.stage}</span>{project.github_url && <Github size={15} />}</div><h3>{project.name}</h3><p>{project.description}</p><small>{date(project.created_at)}</small></button>; }
function PersonRow({ person }: { person: Person }) { return <button className="profile-person-row" onClick={() => nav(`/profile/${encodeURIComponent(person.username)}`)}><Avatar user={person} size={42} /><span><strong>{person.name}</strong><small>@{person.username}</small>{person.bio && <em>{person.bio}</em>}</span><ArrowUpRight size={15} /></button>; }
function AddAgentModal({ onClose, onDone }: { onClose: () => void; onDone: () => void }) { const [agents, setAgents] = useState<User[]>([]); const [query, setQuery] = useState(""); const [role, setRole] = useState(""); const [selected, setSelected] = useState<User | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); useEffect(() => { apiFetch<{ data: User[] }>("/social/affiliations/agents").then((response) => setAgents(response.data ?? [])).catch(() => setAgents([])); }, []); const filtered = agents.filter((agent) => `${agent.name} ${agent.username}`.toLowerCase().includes(query.toLowerCase())); const submit = async () => { if (!selected || !role.trim()) { setError("Select an agent and enter your qualification."); return; } setBusy(true); setError(""); try { await apiFetch("/social/affiliations/requests", { method: "POST", body: JSON.stringify({ agentId: selected.id, role: role.trim() }) }); onDone(); } catch (value) { setError(value instanceof Error ? value.message : "Request could not be sent."); } finally { setBusy(false); } }; return <div className="profile-action-modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="profile-action-modal"><header><div><div className="eyebrow">TRUSTED IDENTITY</div><h2>Add an agent</h2></div><button className="profile-action-modal-close" onClick={onClose} aria-label="Close"><X size={17} /></button></header>{selected ? <div className="profile-selected-agent"><Avatar user={selected} size={42} /><strong>{selected.name}</strong><small>@{selected.username}</small><button onClick={() => setSelected(null)}>Change</button></div> : <><label className="profile-action-field"><span>Search agents</span><div className="profile-action-input"><Search size={15} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search agent name or username" /></div></label><div className="profile-action-results">{filtered.map((agent) => <button className="profile-action-agent" key={agent.id} onClick={() => setSelected(agent)}><Avatar user={agent} size={34} /><span><strong>{agent.name}</strong><small>@{agent.username}</small></span></button>)}</div></>}{selected && <><label className="profile-action-field"><span>What do you do / qualification?</span><input value={role} onChange={(event) => setRole(event.target.value)} placeholder="Founder, Developer, Contributor..." /></label><p className="profile-action-help">The agent must approve this affiliation before it becomes public.</p><button className="profile-tab-action" disabled={busy} onClick={() => void submit()}>{busy ? "Sending..." : "Send verification request"}</button></>}{error && <p className="profile-action-error">{error}</p>}</div></div>; }

export default function ProfileSectionTabs({ username }: { username: string }) {
  const [summary, setSummary] = useState<Summary | null>(null); const [tab, setTab] = useState<Tab>("posts"); const [query, setQuery] = useState(""); const [caches, setCaches] = useState<Record<Tab, Cache>>({ posts: emptyCache(), projects: emptyCache(), followers: emptyCache(), following: emptyCache() }); const [summaryLoading, setSummaryLoading] = useState(true); const [summaryError, setSummaryError] = useState(""); const [addAgentOpen, setAddAgentOpen] = useState(false); const sentinel = useRef<HTMLDivElement | null>(null); const cache = caches[tab];
  const loadSummary = async () => { setSummaryLoading(true); try { const response = await apiFetch<{ data: Summary }>(`/social/users/${encodeURIComponent(username)}/profile-summary`); setSummary(response.data); setSummaryError(""); } catch (value) { setSummaryError(value instanceof Error ? value.message : "Profile could not be loaded."); } finally { setSummaryLoading(false); } };
  useEffect(() => { void loadSummary(); setTab("posts"); setQuery(""); setCaches({ posts: emptyCache(), projects: emptyCache(), followers: emptyCache(), following: emptyCache() }); }, [username]);
  const loadPage = async (kind: Tab, reset = false) => { const current = caches[kind]; if (current.loading || (!current.hasMore && !reset)) return; const nextQuery = reset ? query : current.query; setCaches((value) => ({ ...value, [kind]: { ...value[kind], loading: true, error: "", ...(reset ? { items: [], cursor: null, hasMore: true, query: nextQuery } : {}) } })); try { const params = new URLSearchParams({ type: kind, limit: "15" }); if (nextQuery.trim()) params.set("q", nextQuery.trim()); if (!reset && current.cursor) { params.set("cursorCreatedAt", current.cursor.createdAt); params.set("cursorId", current.cursor.id); } const response = await apiFetch<{ data: Page<Build | Project | Person> }>(`/social/users/${encodeURIComponent(username)}/profile-items?${params}`); setCaches((value) => { const previous = reset ? [] : value[kind].items; const merged = [...previous, ...response.data.items].filter((item, index, list) => list.findIndex((candidate) => (candidate as { id: string }).id === (item as { id: string }).id) === index); return { ...value, [kind]: { items: merged, cursor: response.data.nextCursor, hasMore: response.data.hasMore, loading: false, error: "", query: nextQuery } }; }); } catch (value) { setCaches((state) => ({ ...state, [kind]: { ...state[kind], loading: false, error: value instanceof Error ? value.message : "Could not load this section." } })); } };
  useEffect(() => { void loadPage(tab, true); }, [tab, query]);
  useEffect(() => { const node = sentinel.current; if (!node) return; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) void loadPage(tab); }, { rootMargin: "360px" }); observer.observe(node); return () => observer.disconnect(); }, [tab, cache.cursor, cache.hasMore, cache.loading]);
  const count = (kind: Tab) => summaryLoading ? null : summary?.stats[kind] ?? 0; const own = getSavedUser()?.username?.toLowerCase() === username.toLowerCase();
  const renderContent = () => { if (cache.loading && cache.items.length === 0) return <LoadingRows kind={tab} />; if (cache.error && cache.items.length === 0) return <div className="profile-tab-empty profile-tabs-error"><Activity size={20} /><strong>Could not load this section</strong><span>{cache.error}</span><button className="profile-tab-action" onClick={() => void loadPage(tab, true)}>Try again</button></div>; if (!cache.items.length) return <div className="profile-tab-empty"><Users size={20} /><strong>{tab === "posts" ? "No build notes yet" : tab === "projects" ? "No projects yet" : tab === "followers" ? "No followers yet" : "Not following anyone yet"}</strong></div>; return <>{tab === "posts" ? (cache.items as Build[]).map((item) => <BuildCard key={item.id} build={item} user={summary!.user} />) : tab === "projects" ? (cache.items as Project[]).map((item) => <ProjectCard key={item.id} project={item} />) : (cache.items as Person[]).map((item) => <PersonRow key={item.id} person={item} />)}{cache.loading && <div className="profile-tab-loading-more"><i /> Loading more...</div>}<div ref={sentinel} className="profile-tab-sentinel" />{!cache.hasMore && <div className="profile-tab-end">You are all caught up.</div>}</>; };
  return <section className="profile-section-tabs-wrap"><style>{`.profile-content-grid{display:grid!important;grid-template-columns:minmax(0,1fr) minmax(280px,350px)!important;align-items:start!important;gap:24px!important;width:100%!important;min-width:0!important}.profile-section-content{width:100%!important;min-width:0!important}.profile-right-rail{display:grid!important;grid-template-columns:minmax(0,1fr)!important;gap:14px!important;width:100%!important;min-width:0!important;align-self:start!important}.profile-right-rail>.profile-post-detail-slot{display:block!important;width:100%!important;max-width:100%!important;min-width:0!important;box-sizing:border-box!important}.profile-right-rail>.profile-affiliations-rail{width:100%!important;max-width:100%!important;min-width:0!important;box-sizing:border-box!important}`}</style><nav className="profile-section-tabs" aria-label="Profile sections">{([ ["posts", "Build Notes"], ["projects", "Projects"], ["followers", "Followers"], ["following", "Following"] ] as const).map(([id, label]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}><span>{label}</span>{count(id) === null ? <i className="profile-count-loader" aria-label="Loading count" /> : <b>{count(id)}</b>}</button>)}</nav><div className="profile-content-grid"><div className="profile-section-content"><div className="profile-tab-search"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${tab === "posts" ? "build notes" : tab}`} /></div>{tab === "posts" && own && <ActionBar onClick={openCreatePost} />}{summaryError && !summary && <div className="profile-tab-empty profile-tabs-error"><strong>{summaryError}</strong></div>}{summary && renderContent()}</div><div className="profile-right-rail"><div className="profile-post-detail-slot" aria-live="polite" /><aside className="profile-affiliations-rail"><div className="profile-affiliations-rail-head"><div><div className="eyebrow">TRUSTED IDENTITY</div><h3>Affiliations</h3></div>{own && <button className="profile-tab-action" onClick={() => setAddAgentOpen(true)}><Plus size={14} /> Add Agent</button>}</div>{summary?.affiliations.length ? summary.affiliations.map((aff) => <article className="profile-affiliation-modern" key={aff.id}><div className="profile-affiliation-top"><div className="profile-affiliation-name"><span className="profile-affiliation-badge">{aff.name.slice(0, 1)}</span><span><strong>{aff.name}</strong><small>@{aff.slug}</small></span></div>{aff.verified && <span className="profile-verified-pill"><Check size={12} /> Verified</span>}</div><p>{aff.role} · {aff.type}</p></article>) : <div className="profile-tab-empty"><Users size={20} /><strong>No affiliations yet</strong><span>Verified affiliations will appear here.</span></div>}</aside></div></div>{addAgentOpen && <AddAgentModal onClose={() => setAddAgentOpen(false)} onDone={() => { setAddAgentOpen(false); void loadSummary(); }} />}</section>;
}
function ActionBar({ onClick }: { onClick: () => void }) { return <div className="profile-tab-actionbar"><div className="profile-tab-action-copy"><span className="profile-tab-action-eyebrow">BUILD IN PUBLIC</span><strong>Keep your build log moving.</strong><small>Share progress, experiments and shipped work as posts.</small></div><button className="profile-tab-action" onClick={onClick}><Plus size={15} /> Post a Build</button></div>; }
