"use client";
import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { Check, Clock3, Send } from "lucide-react";
import { apiFetch, getSavedUser } from "@/lib/api";

type Aff={id:string;name:string;role:string};type Request={id:string;agentId:string;agentName:string;currentRole?:string;requestedRole:string;status:string};
const css=`.nerdd-role-upgrade{margin-top:18px;border-top:1px solid #eee8e1;padding-top:18px}.nerdd-role-card{border:1px solid #e0d9d1;border-radius:11px;padding:12px;margin-top:9px;background:#fcfaf7}.nerdd-role-card-head{display:flex;justify-content:space-between;align-items:center;gap:8px}.nerdd-role-card strong{font-size:11px}.nerdd-role-card small{font-size:8px;color:#91877e}.nerdd-role-input{display:flex;gap:6px;margin-top:9px}.nerdd-role-input input{flex:1;min-width:0;border:1px solid #ddd6cc;border-radius:8px;padding:8px;font-size:10px;outline:0}.nerdd-role-input button{border:0;border-radius:8px;background:#211d19;color:#fff;padding:8px 10px;display:flex;align-items:center;gap:4px;font-size:9px;font-weight:800}.nerdd-role-status{font-size:8px;margin-top:7px;color:#9a9087;display:flex;gap:5px;align-items:center}`;
export default function SettingsRoleUpgradeLayer(){const[mount,setMount]=useState<HTMLElement|null>(null);const[affiliations,setAffiliations]=useState<Aff[]>([]);const[requests,setRequests]=useState<Request[]>([]);const[values,setValues]=useState<Record<string,string>>({});const load=()=>{if(!window.location.pathname.startsWith("/settings")){setMount(null);return}const host=document.querySelector<HTMLElement>(".settings-panel");if(!host){setMount(null);return}let node=host.querySelector<HTMLElement>(".nerdd-role-upgrade-mount");if(!node){node=document.createElement("div");node.className="nerdd-role-upgrade-mount";host.appendChild(node)}setMount(node);const user=getSavedUser();if(!user?.username)return;apiFetch<any>(`/social/users/${encodeURIComponent(user.username)}/profile-live`).then(r=>setAffiliations(r.data.affiliations??[])).catch(()=>setAffiliations([]));apiFetch<any>("/social/affiliations/role-requests").then(r=>setRequests(r.data??[])).catch(()=>setRequests([]))};useEffect(()=>{load();const onPop=()=>window.setTimeout(load,0);window.addEventListener("popstate",onPop);return()=>{window.removeEventListener("popstate",onPop);document.querySelectorAll(".nerdd-role-upgrade-mount").forEach(x=>x.remove())}},[]);const submit=async(agentId:string)=>{const requestedRole=values[agentId]?.trim();if(!requestedRole)return;try{await apiFetch("/affiliations/role-requests",{method:"POST",body:JSON.stringify({agentId,requestedRole})});setValues(v=>({...v,[agentId]:""}));load()}catch(e){window.alert(e instanceof Error?e.message:"Role request failed")}};if(!mount)return null;return createPortal(<><style>{css}</style><section className="nerdd-role-upgrade"><div className="eyebrow">ROLE UPGRADES</div><p style={{fontSize:10,color:"#91877e",margin:"4px 0 10px"}}>Request a new role inside an existing verified Agent affiliation. The Agent must approve it before your profile timeline changes.</p>{affiliations.length?affiliations.map(a=>{const pending=requests.find(r=>r.agentId===a.id&&r.status==="pending");return <article className="nerdd-role-card" key={a.id}><div className="nerdd-role-card-head"><span><strong>{a.name}</strong><small>Current role · {a.role}</small></span>{pending?<span className="nerdd-role-status"><Clock3 size={11}/> Pending: {pending.requestedRole}</span>:<Check size={14}/>}</div>{!pending&&<div className="nerdd-role-input"><input value={values[a.id]??""} onChange={e=>setValues(v=>({...v,[a.id]:e.target.value}))} placeholder="Request a new role"/><button onClick={()=>void submit(a.id)}><Send size={11}/> Request</button></div>}</article>}) : <div style={{fontSize:10,color:"#91877e"}}>No active Agent affiliations yet.</div>}</section></>,mount)}
