"use client";
import { useEffect, useState } from "react";
import { ArrowDown, Loader2 } from "lucide-react";
import { apiFetch } from "@/lib/api";

type Mode="for-you"|"network";
export default function FeedUpdatePrompt(){
  const [count,setCount]=useState(0);const[loading,setLoading]=useState(false);const[mode,setMode]=useState<Mode>("for-you");const[ids,setIds]=useState<string[]>([]);
  useEffect(()=>{let alive=true;const getMode=():Mode=>{const active=document.querySelector<HTMLElement>(".home-live-tabs button.active");return active?.textContent?.toLowerCase().includes("network")?"network":"for-you"};const bootstrap=async(nextMode:Mode)=>{try{const response=await apiFetch<any>(`/social/feed?mode=${nextMode}`);const posts=response.data??[];if(alive){setMode(nextMode);setIds(posts.map((post:any)=>String(post.id)));setCount(0)}}catch{}};const initial=getMode();void bootstrap(initial);const timer=window.setInterval(async()=>{const next=getMode();if(next!==mode){await bootstrap(next);return}try{const response=await apiFetch<any>(`/social/feed/recommendation-update?mode=${mode}&ids=${encodeURIComponent(ids.join(","))}`);if(alive)setCount(Math.max(0,Number(response.data?.count??0)))}catch{}},12000);return()=>{alive=false;window.clearInterval(timer)}},[ids,mode]);
  if(count<=0)return null;const refresh=()=>{setLoading(true);window.location.reload()};return <div className="nerdd-feed-update-prompt"><style>{`.nerdd-feed-update-prompt{position:fixed;top:82px;left:50%;transform:translateX(-50%);z-index:850;background:#211d19;color:#fff;border-radius:999px;box-shadow:0 12px 35px rgba(0,0,0,.2);font-size:10px;font-weight:800;border:1px solid rgba(255,255,255,.12)}.nerdd-feed-update-prompt button{border:0;background:none;color:inherit;display:flex;align-items:center;gap:8px;padding:9px 14px;cursor:pointer;font:inherit}.nerdd-feed-update-prompt:hover{transform:translateX(-50%) translateY(-1px);box-shadow:0 15px 40px rgba(0,0,0,.24)}.nerdd-feed-update-prompt span{opacity:.9}@media(max-width:600px){.nerdd-feed-update-prompt{top:70px;font-size:9px}.nerdd-feed-update-prompt button{padding:8px 12px}}`}</style><button onClick={refresh} disabled={loading}>{loading?<Loader2 size={14}/>:<ArrowDown size={14}/>}<span>{loading?"Refreshing…":`New for you · ${count} ${count===1?"post":"posts"}`}</span></button></div>;
}
