"use client";

import { useEffect, useMemo, useState } from "react";
import {
  Activity, ArrowLeft, ArrowRight, ArrowUpRight, Bell, Bookmark, CalendarDays, Check,
  ChevronDown, ChevronRight, Compass, ExternalLink, FileText, Github, Heart, Home,
  Image as ImageIcon, Link2, Loader2, MessageCircle, MoreHorizontal, Plus, Quote, Rocket,
  Search, Send, Settings, Share2, Sparkles, TrendingUp, UserRound, Users, X
} from "lucide-react";
import MessagesPanel from "@/components/messages/MessagesPanel";
import { apiFetch, getAuthToken, getSavedUser, startOAuth, uploadMedia } from "@/lib/api";
import { NerddingApp } from "@/components/layout/NerddingApp";
import "./new-social.css";

type User = { id: string; name: string; username: string; avatarUrl?: string | null; accountType?: string; bio?: string | null; location?: string | null };
type Mention = { kind: "user" | "agent"; id: string; name: string; username: string; avatarUrl?: string | null; verified?: boolean; accountType?: string };
type Project = { id: string; name: string; slug: string; description: string; stage: string; github_url?: string | null; githubUrl?: string | null; agent?: any };
type Post = { id: string; authorId?: string; author: User; text: string; createdAt: string; likes: number; comments: number; reposts: number; saves?: number; liked?: boolean; saved?: boolean; reposted?: boolean; score?: number; project?: Project | null; linkUrl?: string | null; media?: Array<{ publicUrl: string; mimeType: string }>; };

const nav = [
  ["/home", "Home", Home], ["/explore", "Explore", Compass], ["/charts", "Top charts", TrendingUp],
  ["/fundraising", "Fundraising", Rocket], ["/events", "Events", CalendarDays], ["/nerddings", "Your Nerddings", Bookmark],
  ["/messages", "Messages", MessageCircle], ["/notifications", "Notifications", Bell],
] as const;

const go = (href: string) => { window.history.pushState({}, "", href); window.dispatchEvent(new PopStateEvent("popstate")); };
const ago = (value: string) => { const s = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000)); if (s < 60) return "now"; if (s < 3600) return `${Math.floor(s / 60)}m`; if (s < 86400) return `${Math.floor(s / 3600)}h`; return `${Math.floor(s / 86400)}d`; };
const initials = (u?: { name?: string }) => (u?.name ?? "N").split(/\s+/).map((x) => x[0]).join("").slice(0, 2).toUpperCase();

function NSAvatar({ user, size = "sm" }: { user?: User | null; size?: "xs" | "sm" | "md" | "lg" | "xl" }) {
  return <span className={`ns-avatar ns-avatar-${size}`}><>{user?.avatarUrl ? <img src={user.avatarUrl} alt="" /> : initials(user)}</></span>;
}

function LoginGate() {
  return <div className="ns-login"><div className="ns-login-card"><span className="ns-logo">N</span><span className="ns-eyebrow">NERDDINGS</span><h1>Build. Share. <i>Find your people.</i></h1><p>A focused social network for people building, researching and shipping.</p><button onClick={() => startOAuth("google")}><b>G</b> Continue with Google</button><button onClick={() => startOAuth("github")}><Github size={17}/> Continue with GitHub</button></div></div>;
}

function Sidebar({ active, counts, username, onCreate }: { active: string; counts: { messages: number; notifications: number }; username?: string; onCreate: () => void }) {
  return <aside className="ns-sidebar"><button className="ns-brand" onClick={() => go("/home")}><span>N</span><b>nerddings</b></button><div className="ns-nav">{nav.map(([href, label, Icon]) => <button key={href} className={active === href ? "active" : ""} onClick={() => go(href)}><Icon size={19}/><span>{label}</span>{label === "Messages" && counts.messages > 0 && <em>{counts.messages > 99 ? "99+" : counts.messages}</em>}{label === "Notifications" && counts.notifications > 0 && <em>{counts.notifications > 99 ? "99+" : counts.notifications}</em>}</button>)}</div><div className="ns-divider"/><button className={`ns-profile-link ${active.startsWith("/profile") ? "active" : ""}`} onClick={() => username && go(`/profile/${username}`)}><UserRound size={19}/><span>Profile</span></button><button className="ns-create" onClick={onCreate}><Plus size={17}/> Create</button><button className="ns-user" onClick={() => username && go(`/profile/${username}`)}><NSAvatar user={getSavedUser()} size="sm"/><span><b>{getSavedUser()?.name ?? "Member"}</b><small>@{username ?? "member"}</small></span></button></aside>;
}

function Composer({ onClose, onPosted }: { onClose: () => void; onPosted: (p: Post) => void }) {
  const me = getSavedUser();
  const [text, setText] = useState("");
  const [linkUrl, setLinkUrl] = useState("");
  const [files, setFiles] = useState<File[]>([]);
  const [projects, setProjects] = useState<Project[]>([]);
  const [project, setProject] = useState("");
  const [mentionQuery, setMentionQuery] = useState("");
  const [mentions, setMentions] = useState<Mention[]>([]);
  const [busy, setBusy] = useState(false);
  const [uploading, setUploading] = useState(false);

  useEffect(() => { if (!me?.username) return; apiFetch<any>(`/social/users/${encodeURIComponent(me.username)}/profile`).then((r) => setProjects(r.data.projects ?? [])).catch(() => setProjects([])); }, [me?.username]);

  useEffect(() => {
    if (!mentionQuery) { setMentions([]); return; }
    const id = window.setTimeout(() => apiFetch<any>(`/social/mentions?q=${encodeURIComponent(mentionQuery)}`).then((r) => setMentions(r.data ?? [])).catch(() => setMentions([])), 160);
    return () => window.clearTimeout(id);
  }, [mentionQuery]);

  const onTextChange = (value: string) => {
    setText(value);
    const match = value.match(/(?:^|\s)@([a-zA-Z0-9_.-]*)$/);
    setMentionQuery(match ? match[1] : "");
  };
  const chooseMention = (m: Mention) => { const next = text.replace(/(?:^|\s)@([a-zA-Z0-9_.-]*)$/, ` @${m.username} `).trimStart(); setText(next); setMentionQuery(""); setMentions([]); };

  const publish = async () => {
    if (!text.trim() || busy) return;
    setBusy(true);
    try {
      setUploading(files.length > 0);
      const media = await Promise.all(files.map((f) => uploadMedia(f)));
      const result = await apiFetch<any>("/posts", { method: "POST", body: JSON.stringify({ body: text.trim(), media, projectSlug: project || undefined, linkUrl: linkUrl.trim() || undefined }) });
      const p: Post = { id: result.data.id, authorId: me?.id, author: { id: me?.id ?? "", name: me?.name ?? "Member", username: me?.username ?? "member", avatarUrl: me?.avatarUrl, accountType: me?.accountType }, text: text.trim(), createdAt: new Date().toISOString(), likes: 0, comments: 0, reposts: 0, project: projects.find((x) => x.slug === project) ?? null, linkUrl: linkUrl.trim() || null, media };
      onPosted(p); onClose();
    } catch (e) { window.alert(e instanceof Error ? e.message : "Post could not be published."); } finally { setUploading(false); setBusy(false); }
  };

  return <div className="ns-overlay" onMouseDown={(e) => e.currentTarget === e.target && onClose()}><div className="ns-composer"><header><div><span className="ns-eyebrow">SHARE PROGRESS</span><h2>Create post</h2></div><button onClick={onClose}><X size={18}/></button></header><div className="ns-compose-user"><NSAvatar user={me} size="sm"/><span><b>{me?.name ?? "Member"}</b><small>Everyone</small></span></div><div className="ns-compose-body"><textarea autoFocus value={text} onChange={(e) => onTextChange(e.target.value)} placeholder="What are you building, learning, testing or shipping?" maxLength={5000}/>{mentions.length > 0 && <div className="ns-mention-menu">{mentions.map((m) => <button key={`${m.kind}-${m.id}`} onClick={() => chooseMention(m)}><NSAvatar user={{ id: m.id, name: m.name, username: m.username, avatarUrl: m.avatarUrl }} size="xs"/><span><b>{m.name}</b><small>@{m.username} · {m.kind}</small></span>{m.verified && <Check size={13}/>}</button>)}</div>}</div><div className="ns-compose-options"><label><ImageIcon size={16}/><span>{files.length ? `${files.length} media selected` : "Media"}</span><input type="file" multiple accept="image/*,video/*" onChange={(e) => setFiles(Array.from(e.target.files ?? []).slice(0, 10))}/></label><label><Link2 size={16}/><input value={linkUrl} onChange={(e) => setLinkUrl(e.target.value)} placeholder="Optional link"/></label><label><Rocket size={16}/><select value={project} onChange={(e) => setProject(e.target.value)}><option value="">Attach project (optional)</option>{projects.map((p) => <option key={p.id} value={p.slug}>{p.name}</option>)}</select></label></div><footer><span>{text.length}/5000</span><button disabled={!text.trim() || busy} onClick={() => void publish()}>{busy ? <><Loader2 className="spin" size={15}/> {uploading ? "Uploading…" : "Publishing…"}</> : <>Publish <ArrowUpRight size={15}/></>}</button></footer></div></div>;
}

function PostCard({ post, onOpen, onChanged }: { post: Post; onOpen: (p: Post) => void; onChanged: (id: string, patch: Partial<Post>) => void }) {
  const act = async (action: "like" | "save" | "repost") => { if (!getAuthToken()) return go("/login"); try { const r = await apiFetch<any>(`/posts/${post.id}/${action}`, { method: "POST" }); onChanged(post.id, action === "like" ? { liked: r.data.active, likes: post.likes + (r.data.active ? 1 : -1) } : action === "save" ? { saved: r.data.active } : { reposted: r.data.active, reposts: post.reposts + (r.data.active ? 1 : -1) }); } catch { /* keep UI stable */ } };
  return <article className="ns-post"><div className="ns-post-top"><button className="ns-author" onClick={() => go(`/profile/${post.author.username}`)}><NSAvatar user={post.author} size="sm"/><span><b>{post.author.name}</b><small>@{post.author.username} · {ago(post.createdAt)}</small></span></button><button className="ns-quiet"><MoreHorizontal size={17}/></button></div><div className="ns-post-text" onClick={() => onOpen(post)}>{post.text}</div>{post.media?.length ? <div className="ns-media-grid">{post.media.map((m, i) => m.mimeType.startsWith("video") ? <video key={i} controls src={m.publicUrl}/> : <img key={i} src={m.publicUrl} alt=""/>)}</div> : null}{post.project && <button className="ns-post-project" onClick={() => go(`/project/${post.project!.slug}`)}><span><b>{post.project!.name}</b><small>{post.project!.stage} · {post.project!.description}</small></span><ArrowUpRight size={15}/></button>}{post.linkUrl && <a className="ns-post-link" href={post.linkUrl} target="_blank" rel="noreferrer"><Link2 size={14}/><span>{post.linkUrl.replace(/^https?:\/\//, "").slice(0, 90)}</span><ExternalLink size={13}/></a>}<div className="ns-post-stats"><span>{post.likes} likes</span><span>{post.comments} comments</span><span>{post.reposts} nerddings</span>{post.score != null && <span className="ns-score">{Math.round(post.score * 100)} signal</span>}</div><div className="ns-actions"><button className={post.liked ? "on" : ""} onClick={() => void act("like")}><Heart size={16} fill={post.liked ? "currentColor" : "none"}/> Like</button><button onClick={() => onOpen(post)}><MessageCircle size={16}/> Comment</button><button className={post.reposted ? "on" : ""} onClick={() => void act("repost")}><Activity size={16}/> Nerdd</button><button className={post.saved ? "on" : ""} onClick={() => void act("save")}><Bookmark size={16} fill={post.saved ? "currentColor" : "none"}/> Save</button><button onClick={() => onOpen(post)}><Quote size={16}/> Quote</button><button><Share2 size={16}/></button></div></article>;
}

function PostDrawer({ post, onClose }: { post: Post; onClose: () => void }) {
  const [detail, setDetail] = useState<any>(null); const [reply, setReply] = useState("");
  const load = () => apiFetch<any>(`/social/posts/${post.id}`).then((r) => setDetail(r.data)).catch(() => undefined);
  useEffect(() => { void load(); const id = window.setInterval(() => void load(), 2500); return () => window.clearInterval(id); }, [post.id]);
  const add = async () => { if (!reply.trim()) return; await apiFetch(`/social/posts/${post.id}/comments`, { method: "POST", body: JSON.stringify({ body: reply.trim() }) }); setReply(""); void load(); };
  const Comment = ({ item, depth = 0 }: { item: any; depth?: number }) => { const [value, setValue] = useState(""); const [open, setOpen] = useState(false); const send = async () => { if (!value.trim()) return; await apiFetch(`/social/posts/${post.id}/comments`, { method: "POST", body: JSON.stringify({ body: value.trim(), parentId: item.id }) }); setValue(""); setOpen(false); void load(); }; return <div className="ns-comment" style={{ marginLeft: Math.min(depth, 5) * 18 }}><NSAvatar user={item.author} size="xs"/><div><b>{item.author.name}</b><small>@{item.author.username} · {ago(item.createdAt)}</small><p>{item.body}</p><button onClick={() => setOpen(!open)}>Reply</button>{open && <div className="ns-reply"><input value={value} onChange={(e) => setValue(e.target.value)} onKeyDown={(e) => e.key === "Enter" && void send()} placeholder="Reply…"/><button onClick={() => void send()}><Send size={13}/></button></div>}{item.replies?.map((r: any) => <Comment key={r.id} item={r} depth={depth + 1}/>)}</div></div>; };
  return <div className="ns-drawer-backdrop" onMouseDown={(e) => e.currentTarget === e.target && onClose()}><aside className="ns-drawer"><header><div><span className="ns-eyebrow">POST DETAIL</span><h2>Conversation</h2></div><button onClick={onClose}><X size={18}/></button></header><div className="ns-drawer-scroll"><article className="ns-detail-post"><div className="ns-post-top"><div className="ns-author"><NSAvatar user={post.author} size="sm"/><span><b>{post.author.name}</b><small>@{post.author.username} · {ago(post.createdAt)}</small></span></div></div><div className="ns-post-text">{post.text}</div>{post.project && <button className="ns-post-project"><b>{post.project.name}</b><ChevronRight size={14}/></button>}<div className="ns-actions"><span>{detail?.likes ?? post.likes} likes</span><span>{detail?.comments ?? post.comments} comments</span><button><Quote size={15}/> Quote</button></div></article><div className="ns-comment-compose"><NSAvatar user={getSavedUser()} size="xs"/><input value={reply} onChange={(e) => setReply(e.target.value)} onKeyDown={(e) => e.key === "Enter" && void add()} placeholder="Write a thoughtful reply…"/><button disabled={!reply.trim()} onClick={() => void add()}><Send size={15}/></button></div>{detail?.commentsTree?.map((c: any) => <Comment key={c.id} item={c}/>)}</div></aside></div>;
}

function Feed({ mode }: { mode: "for-you" | "network" }) {
  const [posts, setPosts] = useState<Post[]>([]); const [selected, setSelected] = useState<Post | null>(null); const [compose, setCompose] = useState(false); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const r = await apiFetch<any>(`/social/feed?mode=${mode}`); setPosts(r.data ?? []); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [mode]);
  const changed = (id: string, patch: Partial<Post>) => setPosts((v) => v.map((p) => p.id === id ? { ...p, ...patch } : p));
  return <div className="ns-feed-layout"><main className="ns-feed"><div className="ns-tabs"><button className={mode === "for-you" ? "selected" : ""} onClick={() => go("/home")}>For You</button><button className={mode === "network" ? "selected" : ""} onClick={() => go("/home?tab=network")}>Your network</button></div><button className="ns-mini-composer" onClick={() => setCompose(true)}><NSAvatar user={getSavedUser()} size="sm"/><span>Share what you’re building…</span><Plus size={18}/></button>{loading ? <div className="ns-skeletons"><div/><div/><div/></div> : posts.length ? posts.map((p) => <PostCard key={p.id} post={p} onOpen={setSelected} onChanged={changed}/>) : <div className="ns-empty"><Sparkles size={24}/><h3>Your feed is ready for real work.</h3><p>Publish an update or follow builders to shape your network.</p><button onClick={() => setCompose(true)}>Create your first post</button></div>}</main><aside className="ns-right"><section><div className="ns-section-head"><b>Discover</b><button onClick={() => go("/explore")}>Explore <ArrowUpRight size={13}/></button></div><p>Fresh work, useful replies and projects with momentum.</p></section><section><div className="ns-section-head"><b>Rising builders</b><button onClick={() => go("/charts")}>Charts <ArrowUpRight size={13}/></button></div><p>People gaining momentum through consistent work.</p></section></aside>{compose && <Composer onClose={() => setCompose(false)} onPosted={(p) => setPosts((v) => [p, ...v])}/>} {selected && <PostDrawer post={selected} onClose={() => setSelected(null)}/>}</div>;
}

function NotificationsView({ onRead }: { onRead: () => void }) {
  const [items, setItems] = useState<any[]>([]);
  const load = () => apiFetch<any>("/notifications").then((r) => setItems(r.data ?? [])).catch(() => setItems([]));
  useEffect(() => { void load(); }, []);
  const readAll = async () => { await apiFetch("/notifications/read-all", { method: "POST" }); await load(); onRead(); };
  return <div className="ns-page"><div className="ns-page-head"><div><span className="ns-eyebrow">ACTIVITY</span><h1>Notifications</h1></div><button className="ns-outline" onClick={() => void readAll()}><Check size={15}/> Mark all read</button></div><div className="ns-card">{items.length ? items.map((n) => <button key={n.id} className={`ns-notification ${n.readAt ? "" : "unread"}`} onClick={() => { if (n.actor?.username) go(`/profile/${n.actor.username}`); }}><NSAvatar user={n.actor ?? { name: "Nerdding", username: "nerddings" }} size="sm"/><span><b>{n.actor?.name ?? "Nerdding"}</b> {n.text}<small>{ago(n.createdAt)}</small></span>{!n.readAt && <i/>}</button>) : <div className="ns-empty"><Bell size={22}/><h3>No notifications</h3><p>Likes, follows, comments and project activity will appear here.</p></div>}</div></div>;
}

function ProfileView({ username }: { username: string }) {
  const [data, setData] = useState<any>(null); const [following, setFollowing] = useState(false); const [showFollowers, setShowFollowers] = useState(false); const [showFollowing, setShowFollowing] = useState(false);
  useEffect(() => { setData(null); apiFetch<any>(`/social/users/${encodeURIComponent(username)}/profile`).then((r) => { setData(r.data); setFollowing(Boolean(r.data.isFollowing)); }).catch(() => setData({ error: true })); }, [username]);
  if (!data) return <div className="ns-page"><div className="ns-loading">Loading profile…</div></div>;
  if (data.error) return <div className="ns-page"><div className="ns-empty"><UserRound size={22}/><h3>Profile not found</h3><button onClick={() => go("/home")}>Back home</button></div></div>;
  const u = data.user as any;
  const follow = async () => { const r = await apiFetch<any>(`/users/${u.id}/follow`, { method: "POST" }); setFollowing(r.data.active); };
  return <div className="ns-profile-page"><div className="ns-cover"/><div className="ns-profile-head"><NSAvatar user={{ id: u.id, name: u.name, username: u.username, avatarUrl: u.avatar_url ?? u.avatarUrl }} size="xl"/><div className="ns-profile-copy"><div className="ns-profile-title"><div><h1>{u.name}</h1><p>@{u.username} · {u.account_type === "agent" ? "Agent / organization" : "Builder"}{u.location ? ` · ${u.location}` : ""}</p></div><div><button className={following ? "ns-outline" : "ns-primary"} onClick={() => void follow()}>{following ? <><Check size={14}/> Following</> : <><Plus size={14}/> Follow</>}</button></div></div><p>{u.bio || "Building in public on Nerddings."}</p></div></div><div className="ns-statbar"><button onClick={() => setShowFollowers(true)}><b>{data.stats.followers}</b> Followers</button><button onClick={() => setShowFollowing(true)}><b>{data.stats.following}</b> Following</button><span><b>{data.stats.projects}</b> Projects</span><span><b>{data.stats.posts}</b> Posts</span></div>{data.mutualFollowers?.length ? <div className="ns-mutual"><Users size={14}/> Followed by {data.mutualFollowers.slice(0, 3).map((x: any) => x.name).join(", ")}</div> : null}<section className="ns-profile-projects"><div className="ns-section-head"><b>Projects</b><button onClick={() => go(`/project/create?owner=${encodeURIComponent(u.username)}`)}>Create project <Plus size={13}/></button></div><div className="ns-project-grid">{data.projects?.length ? data.projects.map((p: any) => <button className="ns-project-tile" key={p.id} onClick={() => go(`/project/${p.slug}`)}><span>{p.stage}</span><h3>{p.name}</h3><p>{p.description}</p>{p.github_url && <small><Github size={12}/> GitHub linked</small>}</button>) : <div className="ns-empty"><FolderPlaceholder/> <h3>No projects yet</h3><p>Give your work a home.</p></div>}</div></section>{(showFollowers || showFollowing) && <PeopleModal title={showFollowers ? "Followers" : "Following"} items={showFollowers ? data.followers : data.following} onClose={() => { setShowFollowers(false); setShowFollowing(false); }}/>}</div>;
}

function FolderPlaceholder() { return <FileText size={22}/>; }
function PeopleModal({ title, items, onClose }: { title: string; items: any[]; onClose: () => void }) { return <div className="ns-overlay" onMouseDown={(e) => e.currentTarget === e.target && onClose()}><div className="ns-list-modal"><header><b>{title}</b><button onClick={onClose}><X size={18}/></button></header>{items?.length ? items.map((x: any) => <button className="ns-person" key={x.id} onClick={() => { onClose(); go(`/profile/${x.username}`); }}><NSAvatar user={{ id: x.id, name: x.name, username: x.username, avatarUrl: x.avatar_url }} size="sm"/><span><b>{x.name}</b><small>@{x.username}</small></span><ChevronRight size={14}/></button>) : <div className="ns-empty"><Users size={20}/><p>Nothing here yet.</p></div>}</div></div>; }

function ProjectCreate({ onCreated }: { onCreated: (slug: string) => void }) {
  const [agents, setAgents] = useState<any[]>([]); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [stage, setStage] = useState("Idea"); const [agentId, setAgentId] = useState(""); const [githubUrl, setGithubUrl] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { apiFetch<any>("/social/agents").then((r) => setAgents(r.data ?? [])).catch(() => setAgents([])); }, []);
  const submit = async () => { if (!name.trim() || !description.trim()) return; setBusy(true); try { const r = await apiFetch<any>("/social/projects", { method: "POST", body: JSON.stringify({ name, description, stage, agentId: agentId || null, githubUrl: githubUrl || null }) }); onCreated(r.data.slug); } catch (e) { window.alert(e instanceof Error ? e.message : "Project could not be created."); } finally { setBusy(false); } };
  return <div className="ns-page"><div className="ns-page-head"><div><span className="ns-eyebrow">YOUR WORK</span><h1>Create project</h1><p>Give a project a home, connect an organization and invite contributors later.</p></div></div><div className="ns-card ns-form"><label>Name<input value={name} onChange={(e) => setName(e.target.value)} placeholder="Project name"/></label><label>Description<textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="What are you building?"/></label><label>Stage<select value={stage} onChange={(e) => setStage(e.target.value)}><option>Idea</option><option>Prototype</option><option>Building</option><option>Beta</option><option>Launched</option><option>Fundraising</option></select></label><label>Agent / organization<select value={agentId} onChange={(e) => setAgentId(e.target.value)}><option value="">No agent</option>{agents.map((a) => <option key={a.id} value={a.id}>{a.name}{a.verified ? " ✓" : ""}</option>)}</select></label><label>GitHub URL<input value={githubUrl} onChange={(e) => setGithubUrl(e.target.value)} placeholder="https://github.com/owner/repository"/></label><button className="ns-primary" disabled={busy || !name.trim() || !description.trim()} onClick={() => void submit()}>{busy ? "Creating…" : "Create project"} <ArrowRight size={15}/></button></div></div>;
}

function ProjectView({ slug }: { slug: string }) {
  const [project, setProject] = useState<any>(null); const [members, setMembers] = useState<any[]>([]); const [candidate, setCandidate] = useState(""); const [suggestions, setSuggestions] = useState<Mention[]>([]); const [commits, setCommits] = useState<any[]>([]); const [inviting, setInviting] = useState(false);
  const load = () => { apiFetch<any>(`/projects/${encodeURIComponent(slug)}`).then((r) => setProject(r.data)).catch(() => setProject({ error: true })); apiFetch<any>(`/social/projects/${encodeURIComponent(slug)}/members`).then((r) => setMembers(r.data ?? [])).catch(() => setMembers([])); apiFetch<any>(`/social/projects/${encodeURIComponent(slug)}/github-commits`).then((r) => setCommits(r.data ?? [])).catch(() => setCommits([])); };
  useEffect(() => { void load(); }, [slug]);
  useEffect(() => { if (!candidate) { setSuggestions([]); return; } const id = window.setTimeout(() => apiFetch<any>(`/social/mentions?q=${encodeURIComponent(candidate.replace(/^@/, ""))}`).then((r) => setSuggestions(r.data ?? [])).catch(() => setSuggestions([])), 160); return () => window.clearTimeout(id); }, [candidate]);
  if (!project) return <div className="ns-page"><div className="ns-loading">Loading project…</div></div>;
  if (project.error) return <div className="ns-page"><div className="ns-empty"><Rocket size={22}/><h3>Project not found</h3><button onClick={() => go("/home")}>Back home</button></div></div>;
  const invite = async (u: Mention) => { if (u.kind !== "user") return; setInviting(true); try { await apiFetch(`/social/projects/${encodeURIComponent(slug)}/invitations`, { method: "POST", body: JSON.stringify({ userId: u.id }) }); setCandidate(""); setSuggestions([]); window.alert(`Invitation sent to @${u.username}`); } finally { setInviting(false); } };
  return <div className="ns-page"><div className="ns-project-hero"><span className="ns-eyebrow">PROJECT</span><h1>{project.name}</h1><p>{project.description}</p><div className="ns-pills"><span>{project.stage}</span>{project.agent && <button onClick={() => go(`/agent/${project.agent.slug}`)}>Agent: {project.agent.name}</button>}</div></div><div className="ns-project-columns"><main><section className="ns-card"><div className="ns-section-head"><b>Contributors</b><span>{members.length}</span></div>{members.map((m) => <button className="ns-person" key={m.user_id} onClick={() => go(`/profile/${m.username}`)}><NSAvatar user={{ id: m.user_id, name: m.name, username: m.username, avatarUrl: m.avatar_url }} size="sm"/><span><b>{m.name}</b><small>@{m.username}</small></span><span className="ns-contributor">Contributor</span></button>)}{members.length === 0 && <p className="ns-muted">Only the project creator is currently listed.</p>}</section><section className="ns-card"><div className="ns-section-head"><b>Invite contributor</b></div><div className="ns-invite"><Search size={14}/><input value={candidate} onChange={(e) => setCandidate(e.target.value)} placeholder="Search a user to invite"/>{suggestions.length > 0 && <div className="ns-mention-menu ns-invite-menu">{suggestions.filter((x) => x.kind === "user").map((m) => <button key={m.id} onClick={() => void invite(m)} disabled={inviting}><NSAvatar user={{ id: m.id, name: m.name, username: m.username, avatarUrl: m.avatarUrl }} size="xs"/><span><b>{m.name}</b><small>@{m.username}</small></span><Plus size={13}/></button>)}</div>}</div></section></main><aside><section className="ns-card">{project.githubUrl ? <a className="ns-github" href={project.githubUrl} target="_blank" rel="noreferrer"><Github size={18}/><span><b>GitHub repository</b><small>Open source project</small></span><ExternalLink size={14}/></a> : <p className="ns-muted">No GitHub repository connected.</p>}<div className="ns-commit-head"><b>Recent commits</b><span>{commits.length}</span></div>{commits.map((c) => <a className="ns-commit" key={c.sha} href={c.url} target="_blank" rel="noreferrer"><span/><div><b>{c.message}</b><small>{c.author} · {c.date ? new Date(c.date).toLocaleDateString() : ""}</small></div></a>)}</section></aside></div></div>;
}

function ExploreView() { const [data, setData] = useState<any>(null); useEffect(() => { apiFetch<any>("/social/explore/live").then((r) => setData(r.data)).catch(() => setData({ stories: [], topics: [] })); }, []); return <div className="ns-page"><div className="ns-page-head"><div><span className="ns-eyebrow">DISCOVER</span><h1>What’s <i>moving.</i></h1><p>Freshness, velocity, useful discussion and work—not follower count.</p></div></div><div className="ns-explore-grid"><main>{data?.stories?.map((p: Post) => <PostCard key={p.id} post={p} onOpen={() => {}} onChanged={() => {}}/>)}</main><aside className="ns-card"><b>Topics gaining velocity</b>{data?.topics?.map((t: any, i: number) => <button className="ns-topic" key={t.topic}><span>0{i + 1}</span><b>{t.topic}</b><small>{t.posts} posts · {t.engagement} interactions</small></button>)}</aside></div></div>; }
function ChartsView() { const [data, setData] = useState<any>(null); useEffect(() => { apiFetch<any>("/social/charts/live").then((r) => setData(r.data)).catch(() => setData({ risingBuilders: [], topProjects: [] })); }, []); return <div className="ns-page"><div className="ns-page-head"><div><span className="ns-eyebrow">SIGNALS OVER STATUS</span><h1>Top <i>charts.</i></h1><p>Ranked by work, engagement, consistency, trust and collaboration.</p></div></div><section className="ns-card">{data?.risingBuilders?.map((u: any, i: number) => <button className="ns-chart-row" key={u.id} onClick={() => go(`/profile/${u.username}`)}><strong>{String(i + 1).padStart(2, "0")}</strong><NSAvatar user={{ id: u.id, name: u.name, username: u.username, avatarUrl: u.avatar_url }} size="sm"/><span><b>{u.name}</b><small>@{u.username}</small></span><span className="ns-chart-meter"><i style={{ width: `${Math.min(100, 10 + u.posts * 4 + u.likes_received * 2 + u.replies_received * 3)}%` }}/></span><ChevronRight size={14}/></button>)}</section></div>; }

function WorkspacePage({ active }: { active: string }) { return <div className="ns-page"><div className="ns-page-head"><div><span className="ns-eyebrow">NERDDINGS WORKSPACE</span><h1>{active.replace("/", "").replace(/-/g, " ") || "Home"}</h1><p>This surface is now owned by the new social experience. No legacy app shell is rendered here.</p></div></div></div>; }

export default function NewSocialApp() {
  const [path, setPath] = useState(typeof window !== "undefined" ? window.location.pathname : "/home");
  const [query, setQuery] = useState(typeof window !== "undefined" ? new URLSearchParams(window.location.search) : new URLSearchParams());
  const [counts, setCounts] = useState({ messages: 0, notifications: 0 });
  const [createOpen, setCreateOpen] = useState(false);
  const [ready, setReady] = useState(false);
  const me = getSavedUser();

  useEffect(() => { setReady(true); const sync = () => { setPath(window.location.pathname); setQuery(new URLSearchParams(window.location.search)); }; window.addEventListener("popstate", sync); return () => window.removeEventListener("popstate", sync); }, []);
  useEffect(() => { if (!getAuthToken()) return; const load = async () => { const [n, m] = await Promise.allSettled([apiFetch<any>("/notifications"), apiFetch<any>("/social/messages/unread-count")]); setCounts({ notifications: n.status === "fulfilled" ? Number(n.value.unreadCount ?? 0) : 0, messages: m.status === "fulfilled" ? Number(m.value.data?.unreadCount ?? 0) + Number(m.value.data?.pendingRequests ?? 0) : 0 }); }; void load(); const id = window.setInterval(() => void load(), 10000); return () => window.clearInterval(id); }, []);

  if (!ready) return <div className="ns-boot"><span>N</span></div>;
  if (path.startsWith("/login") || path.startsWith("/register") || path.startsWith("/auth/callback") || path.startsWith("/onboarding") || path.startsWith("/privacy") || path.startsWith("/terms") || path.startsWith("/cookies") || path.startsWith("/community-guidelines")) return <NerddingApp/>;
  if (!getAuthToken()) return <LoginGate/>;

  const active = path.startsWith("/profile") ? "/profile" : path.startsWith("/project") ? "/project" : nav.find(([href]) => path === href || path.startsWith(`${href}/`))?.[0] ?? "/home";
  const content = path.startsWith("/notifications") ? <NotificationsView onRead={() => setCounts((c) => ({ ...c, notifications: 0 }))}/> : path.startsWith("/profile/") ? <ProfileView username={decodeURIComponent(path.split("/")[2] || me?.username || "")}/> : path === "/profile" ? <ProfileView username={me?.username || ""}/> : path.startsWith("/project/create") ? <ProjectCreate onCreated={(slug) => go(`/project/${slug}`)}/> : path.startsWith("/project/") ? <ProjectView slug={decodeURIComponent(path.split("/")[2] || "")}/> : path.startsWith("/explore") ? <ExploreView/> : path.startsWith("/charts") ? <ChartsView/> : path.startsWith("/messages") ? <MessagesPanel/> : path === "/home" ? <Feed mode={query.get("tab") === "network" ? "network" : "for-you"}/> : <WorkspacePage active={active}/>;

  return <div className="ns-app"><Sidebar active={active} counts={counts} username={me?.username} onCreate={() => setCreateOpen(true)}/><main className="ns-main"><header className="ns-header"><div className="ns-header-title">{active === "/profile" ? "Profile" : active.replace("/", "").replace(/-/g, " ") || "Home"}</div><div className="ns-global-search"><Search size={15}/><input placeholder="Search people, projects, ideas" onKeyDown={(e) => { if (e.key === "Enter") go(`/explore?q=${encodeURIComponent((e.target as HTMLInputElement).value)}`); }}/></div><div className="ns-header-actions"><button onClick={() => go("/notifications")} className={counts.notifications ? "has-count" : ""}><Bell size={18}/>{counts.notifications > 0 && <i>{counts.notifications > 99 ? "99+" : counts.notifications}</i>}</button><button className="ns-header-create" onClick={() => setCreateOpen(true)}><Plus size={15}/> Create</button><button onClick={() => go(`/profile/${me?.username}`)}><NSAvatar user={me} size="sm"/></button></div></header><div className="ns-content">{content}</div></main>{createOpen && <CreateMenu onClose={() => setCreateOpen(false)}/>}</div>;
}

function CreateMenu({ onClose }: { onClose: () => void }) { return <div className="ns-overlay" onMouseDown={(e) => e.currentTarget === e.target && onClose()}><div className="ns-create-menu"><header><div><span className="ns-eyebrow">MAKE SOMETHING</span><h2>Create</h2></div><button onClick={onClose}><X size={18}/></button></header><button onClick={() => { onClose(); go("/home?compose=1"); window.setTimeout(() => window.dispatchEvent(new CustomEvent("nerdding:new-compose")), 0); }}><MessageCircle size={18}/><span><b>Post an update</b><small>Share work, ideas, media and links</small></span><ArrowUpRight size={14}/></button><button onClick={() => { onClose(); go(`/project/create?owner=${encodeURIComponent(getSavedUser()?.username ?? "")}`); }}><Rocket size={18}/><span><b>Create a project</b><small>Connect an agent and GitHub, then invite contributors</small></span><ArrowUpRight size={14}/></button></div></div>; }
