"use client";

import { useEffect, useState } from "react";
import { NerddingApp } from "@/components/layout/NerddingApp";
import { ProfileSurface, SettingsSurface } from "@/components/app/NerddingRouteSurfaces";
import ProjectDetailSurface from "@/components/app/ProjectDetailSurface";
import PostDetailSurface from "@/components/app/PostDetailSurface";
import "@/components/app/nerdding-route-surfaces.css";
import AgentVerificationGate2 from "@/components/agent/AgentVerificationGate2";
import AgentVerificationRedirect from "@/components/agent/AgentVerificationRedirect";
import AgentRouteShield from "@/components/agent/AgentRouteShield";
import AgentLoginLink from "@/components/agent/AgentLoginLink";
import AgentPendingNotice from "@/components/agent/AgentPendingNotice";
import CreateSurface from "@/components/app/CreateSurface";
import ProjectSurface from "@/components/app/ProjectSurface";
import RouteSkeleton from "@/components/app/RouteSkeleton";

const MESSAGE_CACHE_PREFIX = "nerdding.messages.v2.";
function repairMessageCache(){if(typeof window==="undefined")return;const remove:string[]=[];for(let i=0;i<window.localStorage.length;i++){const key=window.localStorage.key(i);if(!key?.startsWith(MESSAGE_CACHE_PREFIX))continue;try{const raw=window.localStorage.getItem(key);if(!raw)continue;const parsed=JSON.parse(raw);if(!Array.isArray(parsed))remove.push(key)}catch{remove.push(key)}}for(const key of remove)window.localStorage.removeItem(key)}
function AppSkeleton(){return <><style>{`.client-app-skeleton{min-height:100dvh;display:grid;grid-template-columns:244px minmax(0,1fr);background:#f8f6f2}.client-app-skeleton-sidebar{padding:24px 14px;border-right:1px solid #e4ded5;background:#fbfaf7}.client-app-skeleton-logo,.client-app-skeleton-nav,.client-app-skeleton-topbar,.client-app-skeleton-card{background:#e8e3dc;position:relative;overflow:hidden}.client-app-skeleton-logo{height:30px;width:125px;border-radius:8px;margin:3px 10px 28px}.client-app-skeleton-nav{height:40px;border-radius:10px;margin:7px 4px}.client-app-skeleton-topbar{height:66px;border-bottom:1px solid #e4ded5;background:#fbfaf7}.client-app-skeleton-content{width:min(1150px,calc(100% - 48px));margin:28px auto;display:grid;gap:14px}.client-app-skeleton-card{height:150px;border-radius:15px}.client-app-skeleton-card.large{height:250px}.client-app-skeleton-logo:after,.client-app-skeleton-nav:after,.client-app-skeleton-topbar:after,.client-app-skeleton-card:after{content:"";position:absolute;inset:0;transform:translateX(-100%);background:linear-gradient(90deg,transparent,rgba(255,255,255,.7),transparent);animation:client-app-shimmer 1.15s infinite}@keyframes client-app-shimmer{to{transform:translateX(100%)}}@media(max-width:760px){.client-app-skeleton{display:block}.client-app-skeleton-sidebar{display:none}.client-app-skeleton-content{width:calc(100% - 20px);margin:18px auto}}`}</style><div className="client-app-skeleton" aria-hidden="true"><aside className="client-app-skeleton-sidebar"><div className="client-app-skeleton-logo"/>{Array.from({length:9},(_,i)=><div className="client-app-skeleton-nav" key={i}/>)}</aside><main><div className="client-app-skeleton-topbar"/><div className="client-app-skeleton-content"><div className="client-app-skeleton-card large"/><div className="client-app-skeleton-card"/><div className="client-app-skeleton-card"/></div></main></div></>}
export default function ClientAppGate(){const[ready,setReady]=useState(false);const[path,setPath]=useState(()=>typeof window==="undefined"?"/":window.location.pathname);useEffect(()=>{repairMessageCache();const onPop=()=>setPath(window.location.pathname);const onComment=async(e:MouseEvent)=>{const target=e.target as HTMLElement|null;const button=target?.closest(".social-actions button") as HTMLButtonElement|null;if(!button)return;const parent=button.parentElement;if(!parent||parent.querySelectorAll("button")[1]!==button)return;const card=button.closest(".social-post-card") as HTMLElement|null;const copy=card?.querySelector(".social-post-copy")?.textContent?.trim();if(!copy)return;e.preventDefault();e.stopPropagation();try{const r=await fetch(`${window.location.origin}/api/v1/social/feed?mode=for-you`,{credentials:"include"});const json=await r.json();const match=(json?.data??[]).find((post:{text?:string})=>post.text?.trim()===copy);if(match?.id){window.history.pushState({},"",`/post/${match.id}`);window.dispatchEvent(new PopStateEvent("popstate"))}}catch{}};window.addEventListener("popstate",onPop);document.addEventListener("click",onComment,true);setReady(true);return()=>{window.removeEventListener("popstate",onPop);document.removeEventListener("click",onComment,true)}},[]);if(!ready)return <AppSkeleton/>;const profile=path.startsWith("/profile/");const settings=path.startsWith("/settings");const project=path.startsWith("/project/")&&path!=="/project/new";const post=path.startsWith("/post/");return <><NerddingApp/>{profile&&<ProfileSurface username={decodeURIComponent(path.split("/")[2]||"")}/>} {settings&&<SettingsSurface/>}{project&&<ProjectDetailSurface slug={decodeURIComponent(path.split("/")[2]||"")}/>} {post&&<PostDetailSurface postId={decodeURIComponent(path.split("/")[2]||"")}/>}<AgentRouteShield/><AgentVerificationGate2/><AgentVerificationRedirect/><AgentLoginLink/><AgentPendingNotice/><CreateSurface/>{path==="/project/new"&&<ProjectSurface/>}<RouteSkeleton/></>}
